//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace test
{
    using System;
    using System.Collections.Generic;
    
    public partial class album
    {
        public int idAlbum { get; set; }
        public string nombre { get; set; }
        public string genero { get; set; }
        public Nullable<System.DateTime> fecha { get; set; }
        public Nullable<int> idArtista { get; set; }
    
        public virtual artista artista { get; set; }
    }
}
